# Generated by Django 5.1.4 on 2024-12-16 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_name', models.CharField(max_length=200)),
                ('prog_duration', models.CharField(max_length=200)),
                ('prog_desc', models.CharField(max_length=200)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Program_created_by', to=settings.AUTH_USER_MODEL)),
                ('prog_inst_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutes.institute_details')),
                ('prog_inst_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutes.institute_type')),
                ('prog_university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.university_details')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Program_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program_Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_rev_start_dt', models.DateField()),
                ('prog_rev_end_dt', models.DateField()),
                ('prog_rev_name', models.CharField(max_length=200)),
                ('prog_rev_desc', models.CharField(max_length=200)),
                ('prog_rev_status', models.CharField(max_length=200)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Program_Revision_created_by', to=settings.AUTH_USER_MODEL)),
                ('prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Program_Revision_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
